"""
gen.py - Generate src/tables.asm and src/font.asm for RetCon 2026 Spectrum demo.
Run from the retcon/ directory: python tools/gen.py
"""
import math, os

# ── Spectrum screen constants ─────────────────────────────────────────────────
SW, SH = 256, 192

# ── Letter raw data (100×100 unit space, direct from HTML spec) ───────────────
BASE = {
    'W': [[10,10],[30,90],[50,50],[70,90],[90,10],[90,10],[90,10]],
    'E': [[80,10],[20,10],[20,50],[80,50],[20,50],[20,90],[80,90]],
    'L': [[20,10],[20,90],[80,90],[80,90],[80,90],[80,90],[80,90]],
    'C': [[80,10],[20,10],[20,90],[80,90],[80,90],[80,90],[80,90]],
    'O': [[80,10],[20,10],[20,90],[80,90],[80,10],[80,10],[80,10]],
    'M': [[10,90],[10,10],[50,60],[90,10],[90,90],[90,90],[90,90]],
    'T': [[20,10],[80,10],[50,10],[50,90],[50,90],[50,90],[50,90]],
    'R': [[20,90],[20,10],[80,10],[80,50],[20,50],[80,90],[80,90]],
    'N': [[20,90],[20,10],[80,90],[80,10],[80,10],[80,10],[80,10]],
    '2': [[20,10],[80,10],[80,50],[20,90],[80,90],[80,90],[80,90]],
    '6': [[80,10],[20,10],[20,90],[80,90],[80,50],[20,50],[20,50]],
    '0': [[20,10],[80,10],[80,90],[20,90],[20,10],[20,10],[20,10]],
}

LINE1 = ['W','E','L','C','O','M','E','T','O']
LINE2 = ['R','E','T','C','O','N','2','0','2','6']

# ── Scale/position matching HTML spec, adapted for 256×192 ───────────────────
REST_Y1_PARAM = round(SH * 0.18)   # = 35  (translation param, not letter centre)
REST_Y2_PARAM = round(SH * 0.52)   # = 100

n1, n2 = len(LINE1), len(LINE2)
hspace1 = SW / (n1 + 1)            # = 25.6
hspace2 = SW / (n2 + 1)            # = 23.27
sfx1 = hspace1 / 100               # x-scale, line 1
sfx2 = hspace2 / 100               # x-scale, line 2
sfy  = (SH * 0.22) / 100           # y-scale, both lines = 0.4224

# ── Easing functions ──────────────────────────────────────────────────────────
def ease_in_out(t):
    return 2*t*t if t < 0.5 else -1 + (4 - 2*t)*t

def ease_in(t):
    return t * t

# ── Build a single letter: returns (cx, cy, offsets_from_center) ─────────────
def build_letter(key, sfx, rest_y_param, hspace, idx):
    raw = BASE[key]
    pts = [(px*sfx + hspace*(idx+1) - sfx*50, py*sfy + rest_y_param) for px,py in raw]
    xs, ys = [p[0] for p in pts], [p[1] for p in pts]
    cx = (min(xs) + max(xs)) / 2
    cy = (min(ys) + max(ys)) / 2
    offsets = [(round(px - cx), round(py - cy)) for px, py in pts]
    return cx, cy, offsets

# Build all 19 letter positions
letters = []
for i, k in enumerate(LINE1):
    cx, cy, off = build_letter(k, sfx1, REST_Y1_PARAM, hspace1, i)
    letters.append(dict(key=k, line=1, cx=cx, cy=cy, offsets=off))
for i, k in enumerate(LINE2):
    cx, cy, off = build_letter(k, sfx2, REST_Y2_PARAM, hspace2, i)
    letters.append(dict(key=k, line=2, cx=cx, cy=cy, offsets=off))

# Scroll travel (matching HTML: travel = REST_Y_PARAM + SH*0.25)
LINE1_TRAVEL = REST_Y1_PARAM + SH * 0.25   # ≈ 83
LINE2_TRAVEL = REST_Y2_PARAM + SH * 0.25   # ≈ 148

# Scroll start = letter centre Y - travel
cy1 = letters[0]['cy']           # representative line 1 centre Y (all share same cy)
cy2 = letters[9]['cy']           # representative line 2 centre Y

scroll1_start = cy1 - LINE1_TRAVEL
scroll2_start = cy2 - LINE2_TRAVEL

# ── DEFB/DEFW helpers ─────────────────────────────────────────────────────────
def defb_rows(vals, per_row=16):
    rows = []
    for s in range(0, len(vals), per_row):
        chunk = vals[s:s+per_row]
        rows.append('    DEFB ' + ','.join(str(v) for v in chunk))
    return rows

def sb(v):
    """Clamp and convert to signed byte representation for DEFB."""
    v = max(-128, min(127, round(v)))
    return v if v >= 0 else v + 256  # PASMO accepts 0-255 in DEFB

# ═══════════════════════════════════════════════════════════════════════════════
# Generate src/tables.asm
# ═══════════════════════════════════════════════════════════════════════════════
lines = [
    '; tables.asm — precomputed lookup tables for RetCon 2026',
    '; Generated by tools/gen.py — do not edit by hand',
    '',
]

# 1. Sine table (256 signed bytes, range -127..+127)
lines += ['; sin_tab: 256 entries, sin_tab[i] = round(sin(i/256*2pi)*127)', 'sin_tab:']
vals = [sb(math.sin(i/256 * 2*math.pi) * 127) for i in range(256)]
lines += defb_rows(vals)
lines.append('')

# 2. Pixel bitmask table
lines += [
    '; bit_tab: bitmask for pixel x within byte, index = x & 7',
    'bit_tab:',
    '    DEFB 0x80,0x40,0x20,0x10,0x08,0x04,0x02,0x01',
    '',
]

# 3. Screen row address table (192 words)
lines += ['; row_addr: base pixel address for each screen row y (0-191)', 'row_addr:']
for y in range(192):
    addr = 0x4000 | ((y & 0xC0) << 5) | ((y & 0x38) << 2) | ((y & 0x07) << 8)
    lines.append(f'    DEFW 0x{addr:04X}  ; row {y}')
lines.append('')

# 4. Scroll Y tables — centre Y of each line per frame (signed bytes)
# Frame 0 = off-screen above, frame 69 = rest position
lines += [f'; scroll_y1: centre Y of line-1 letters per scroll frame (start={round(scroll1_start)}, end={round(cy1)})', 'scroll_y1:']
vals = [sb(scroll1_start + ease_in_out(f/69) * (cy1 - scroll1_start)) for f in range(70)]
lines += defb_rows(vals)
lines.append('')

lines += [f'; scroll_y2: centre Y of line-2 letters per scroll frame (start={round(scroll2_start)}, end={round(cy2)})', 'scroll_y2:']
vals = [sb(scroll2_start + ease_in_out(f/69) * (cy2 - scroll2_start)) for f in range(70)]
lines += defb_rows(vals)
lines.append('')

# 5. Spin angle table — sin_tab index per spin frame (easeIn = t^2, full 360 in 100 frames)
lines += ['; spin_ang: sin_tab index for spin rotation per frame, easeIn curve', 'spin_ang:']
vals = [round((f/99)**2 * 256) & 0xFF for f in range(100)]
lines += defb_rows(vals)
lines.append('')

# 6. Orbit scale table — extra orbit radius per frame (0..13 pixels)
# Radius goes from BASE_ORBIT to BASE_ORBIT+13 and back via sine
# (1 - cos(t/150*2pi)) / 2 * 0.4 * 64, range 0..~12.8 -> 0..13
BASE_ORBIT = 12
lines += [f'; orb_scale: extra orbit radius per frame (add to {BASE_ORBIT}), peak ~13 at frame 75', 'orb_scale:']
vals = [round((1 - math.cos(f/150 * 2*math.pi)) / 2 * 0.4 * 64) for f in range(150)]
lines += defb_rows(vals)
lines.append('')

# 7. Orbit phase offset table — sin_tab index offset per letter
lines += ['; orb_phase: per-letter sin_tab index offset for orbit phase stagger', 'orb_phase:']
vals = [round(i * 256 / 19) & 0xFF for i in range(19)]
lines.append('    DEFB ' + ','.join(str(v) for v in vals))
lines.append('')

# 8. Reset Y tables — slide letters off-screen upward (35 frames, easeIn)
lines += [f'; reset_y1: centre Y of line-1 letters during reset (rest→off-screen)', 'reset_y1:']
vals = [sb(cy1 + ease_in(f/34) * (scroll1_start - cy1)) for f in range(35)]
lines += defb_rows(vals)
lines.append('')

lines += [f'; reset_y2: centre Y of line-2 letters during reset (rest→off-screen)', 'reset_y2:']
vals = [sb(cy2 + ease_in(f/34) * (scroll2_start - cy2)) for f in range(35)]
lines += defb_rows(vals)
lines.append('')

os.makedirs('src', exist_ok=True)
with open('src/tables.asm', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('Wrote src/tables.asm')

# ═══════════════════════════════════════════════════════════════════════════════
# Generate src/font.asm
# ═══════════════════════════════════════════════════════════════════════════════
lines = [
    '; font.asm — letter shape offsets and rest positions for RetCon 2026',
    '; Generated by tools/gen.py — do not edit by hand',
    '; Each letter: 7 x (signed dx, signed dy) offsets from letter centre (pixels)',
    '',
]

# Letter shapes: 7 x (dx, dy) per letter, stored as signed bytes (as 0-255 DEFB values)
lines.append('; letter_shapes: 19 x 14 bytes (7 points x 2 bytes each)')
lines.append('letter_shapes:')
for l in letters:
    offsets = l['offsets']
    vals = []
    for dx, dy in offsets:
        vals.append(sb(dx))
        vals.append(sb(dy))
    comment = f"; {l['key']} (line {l['line']}, cx={round(l['cx'])}, cy={round(l['cy'])})"
    lines.append(f"    DEFB {','.join(str(v) for v in vals)}  {comment}")
lines.append('')

# Rest positions: 19 x (cx, cy) as bytes
lines.append('; rest_pos: 19 x 2 bytes — (cx, cy) screen pixel centre of each letter at rest')
lines.append('rest_pos:')
for l in letters:
    cx, cy = round(l['cx']), round(l['cy'])
    lines.append(f"    DEFB {cx},{cy}  ; {l['key']} line {l['line']}")
lines.append('')

# Sprite blit byte: the screen byte column where each letter's 4-byte sprite starts.
# sprite covers screen x from (blit_byte*8) to (blit_byte*8)+31.
# Chosen so letter centre at cx maps to sprite bit (cx - blit_byte*8) which is 8..23.
lines.append('; sprite_blit_byte: 19 bytes — screen byte column for 4-byte sprite blit')
lines.append('sprite_blit_byte:')
blit_bytes = [max(0, (round(l['cx']) - 16) >> 3) for l in letters]
lines.append('    DEFB ' + ','.join(str(v) for v in blit_bytes))
lines.append('')

# Also print so we can sanity-check
print('sprite_blit_bytes:', blit_bytes)

with open('src/font.asm', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')
print('Wrote src/font.asm')

# ── Summary ───────────────────────────────────────────────────────────────────
print()
print('Letter centres:')
for i, l in enumerate(letters):
    print(f"  [{i:2d}] {l['key']} line{l['line']}  cx={round(l['cx']):3d}  cy={round(l['cy']):3d}")
print()
print(f'scroll_y1: {round(scroll1_start)} -> {round(cy1)}')
print(f'scroll_y2: {round(scroll2_start)} -> {round(cy2)}')
print(f'orbit radius: {BASE_ORBIT} + 0..13 pixels')
