; font.asm — letter shape offsets and rest positions for RetCon 2026
; Generated by tools/gen.py — do not edit by hand
; Each letter: 7 x (signed dx, signed dy) offsets from letter centre (pixels)

; letter_shapes: 19 x 14 bytes (7 points x 2 bytes each)
letter_shapes:
    DEFB 246,239,251,17,0,0,5,17,10,239,10,239,10,239  ; W (line 1, cx=26, cy=56)
    DEFB 8,239,248,239,248,0,8,0,248,0,248,17,8,17  ; E (line 1, cx=51, cy=56)
    DEFB 248,239,248,17,8,17,8,17,8,17,8,17,8,17  ; L (line 1, cx=77, cy=56)
    DEFB 8,239,248,239,248,17,8,17,8,17,8,17,8,17  ; C (line 1, cx=102, cy=56)
    DEFB 8,239,248,239,248,17,8,17,8,239,8,239,8,239  ; O (line 1, cx=128, cy=56)
    DEFB 246,17,246,239,0,4,10,239,10,17,10,17,10,17  ; M (line 1, cx=154, cy=56)
    DEFB 8,239,248,239,248,0,8,0,248,0,248,17,8,17  ; E (line 1, cx=179, cy=56)
    DEFB 248,239,8,239,0,239,0,17,0,17,0,17,0,17  ; T (line 1, cx=205, cy=56)
    DEFB 8,239,248,239,248,17,8,17,8,239,8,239,8,239  ; O (line 1, cx=230, cy=56)
    DEFB 249,17,249,239,7,239,7,0,249,0,7,17,7,17  ; R (line 2, cx=23, cy=121)
    DEFB 7,239,249,239,249,0,7,0,249,0,249,17,7,17  ; E (line 2, cx=47, cy=121)
    DEFB 249,239,7,239,0,239,0,17,0,17,0,17,0,17  ; T (line 2, cx=70, cy=121)
    DEFB 7,239,249,239,249,17,7,17,7,17,7,17,7,17  ; C (line 2, cx=93, cy=121)
    DEFB 7,239,249,239,249,17,7,17,7,239,7,239,7,239  ; O (line 2, cx=116, cy=121)
    DEFB 249,17,249,239,7,17,7,239,7,239,7,239,7,239  ; N (line 2, cx=140, cy=121)
    DEFB 249,239,7,239,7,0,249,17,7,17,7,17,7,17  ; 2 (line 2, cx=163, cy=121)
    DEFB 249,239,7,239,7,17,249,17,249,239,249,239,249,239  ; 0 (line 2, cx=186, cy=121)
    DEFB 249,239,7,239,7,0,249,17,7,17,7,17,7,17  ; 2 (line 2, cx=209, cy=121)
    DEFB 7,239,249,239,249,17,7,17,7,0,249,0,249,0  ; 6 (line 2, cx=233, cy=121)

; rest_pos: 19 x 2 bytes — (cx, cy) screen pixel centre of each letter at rest
rest_pos:
    DEFB 26,56  ; W line 1
    DEFB 51,56  ; E line 1
    DEFB 77,56  ; L line 1
    DEFB 102,56  ; C line 1
    DEFB 128,56  ; O line 1
    DEFB 154,56  ; M line 1
    DEFB 179,56  ; E line 1
    DEFB 205,56  ; T line 1
    DEFB 230,56  ; O line 1
    DEFB 23,121  ; R line 2
    DEFB 47,121  ; E line 2
    DEFB 70,121  ; T line 2
    DEFB 93,121  ; C line 2
    DEFB 116,121  ; O line 2
    DEFB 140,121  ; N line 2
    DEFB 163,121  ; 2 line 2
    DEFB 186,121  ; 0 line 2
    DEFB 209,121  ; 2 line 2
    DEFB 233,121  ; 6 line 2

; sprite_blit_byte: 19 bytes — screen byte column for 4-byte sprite blit
sprite_blit_byte:
    DEFB 1,4,7,10,14,17,20,23,26,0,3,6,9,12,15,18,21,24,27

