; tables.asm — precomputed lookup tables for RetCon 2026
; Generated by tools/gen.py — do not edit by hand

; sin_tab: 256 entries, sin_tab[i] = round(sin(i/256*2pi)*127)
sin_tab:
    DEFB 0,3,6,9,12,16,19,22,25,28,31,34,37,40,43,46
    DEFB 49,51,54,57,60,63,65,68,71,73,76,78,81,83,85,88
    DEFB 90,92,94,96,98,100,102,104,106,107,109,111,112,113,115,116
    DEFB 117,118,120,121,122,122,123,124,125,125,126,126,126,127,127,127
    DEFB 127,127,127,127,126,126,126,125,125,124,123,122,122,121,120,118
    DEFB 117,116,115,113,112,111,109,107,106,104,102,100,98,96,94,92
    DEFB 90,88,85,83,81,78,76,73,71,68,65,63,60,57,54,51
    DEFB 49,46,43,40,37,34,31,28,25,22,19,16,12,9,6,3
    DEFB 0,253,250,247,244,240,237,234,231,228,225,222,219,216,213,210
    DEFB 207,205,202,199,196,193,191,188,185,183,180,178,175,173,171,168
    DEFB 166,164,162,160,158,156,154,152,150,149,147,145,144,143,141,140
    DEFB 139,138,136,135,134,134,133,132,131,131,130,130,130,129,129,129
    DEFB 129,129,129,129,130,130,130,131,131,132,133,134,134,135,136,138
    DEFB 139,140,141,143,144,145,147,149,150,152,154,156,158,160,162,164
    DEFB 166,168,171,173,175,178,180,183,185,188,191,193,196,199,202,205
    DEFB 207,210,213,216,219,222,225,228,231,234,237,240,244,247,250,253

; bit_tab: bitmask for pixel x within byte, index = x & 7
bit_tab:
    DEFB 0x80,0x40,0x20,0x10,0x08,0x04,0x02,0x01

; row_addr: base pixel address for each screen row y (0-191)
row_addr:
    DEFW 0x4000  ; row 0
    DEFW 0x4100  ; row 1
    DEFW 0x4200  ; row 2
    DEFW 0x4300  ; row 3
    DEFW 0x4400  ; row 4
    DEFW 0x4500  ; row 5
    DEFW 0x4600  ; row 6
    DEFW 0x4700  ; row 7
    DEFW 0x4020  ; row 8
    DEFW 0x4120  ; row 9
    DEFW 0x4220  ; row 10
    DEFW 0x4320  ; row 11
    DEFW 0x4420  ; row 12
    DEFW 0x4520  ; row 13
    DEFW 0x4620  ; row 14
    DEFW 0x4720  ; row 15
    DEFW 0x4040  ; row 16
    DEFW 0x4140  ; row 17
    DEFW 0x4240  ; row 18
    DEFW 0x4340  ; row 19
    DEFW 0x4440  ; row 20
    DEFW 0x4540  ; row 21
    DEFW 0x4640  ; row 22
    DEFW 0x4740  ; row 23
    DEFW 0x4060  ; row 24
    DEFW 0x4160  ; row 25
    DEFW 0x4260  ; row 26
    DEFW 0x4360  ; row 27
    DEFW 0x4460  ; row 28
    DEFW 0x4560  ; row 29
    DEFW 0x4660  ; row 30
    DEFW 0x4760  ; row 31
    DEFW 0x4080  ; row 32
    DEFW 0x4180  ; row 33
    DEFW 0x4280  ; row 34
    DEFW 0x4380  ; row 35
    DEFW 0x4480  ; row 36
    DEFW 0x4580  ; row 37
    DEFW 0x4680  ; row 38
    DEFW 0x4780  ; row 39
    DEFW 0x40A0  ; row 40
    DEFW 0x41A0  ; row 41
    DEFW 0x42A0  ; row 42
    DEFW 0x43A0  ; row 43
    DEFW 0x44A0  ; row 44
    DEFW 0x45A0  ; row 45
    DEFW 0x46A0  ; row 46
    DEFW 0x47A0  ; row 47
    DEFW 0x40C0  ; row 48
    DEFW 0x41C0  ; row 49
    DEFW 0x42C0  ; row 50
    DEFW 0x43C0  ; row 51
    DEFW 0x44C0  ; row 52
    DEFW 0x45C0  ; row 53
    DEFW 0x46C0  ; row 54
    DEFW 0x47C0  ; row 55
    DEFW 0x40E0  ; row 56
    DEFW 0x41E0  ; row 57
    DEFW 0x42E0  ; row 58
    DEFW 0x43E0  ; row 59
    DEFW 0x44E0  ; row 60
    DEFW 0x45E0  ; row 61
    DEFW 0x46E0  ; row 62
    DEFW 0x47E0  ; row 63
    DEFW 0x4800  ; row 64
    DEFW 0x4900  ; row 65
    DEFW 0x4A00  ; row 66
    DEFW 0x4B00  ; row 67
    DEFW 0x4C00  ; row 68
    DEFW 0x4D00  ; row 69
    DEFW 0x4E00  ; row 70
    DEFW 0x4F00  ; row 71
    DEFW 0x4820  ; row 72
    DEFW 0x4920  ; row 73
    DEFW 0x4A20  ; row 74
    DEFW 0x4B20  ; row 75
    DEFW 0x4C20  ; row 76
    DEFW 0x4D20  ; row 77
    DEFW 0x4E20  ; row 78
    DEFW 0x4F20  ; row 79
    DEFW 0x4840  ; row 80
    DEFW 0x4940  ; row 81
    DEFW 0x4A40  ; row 82
    DEFW 0x4B40  ; row 83
    DEFW 0x4C40  ; row 84
    DEFW 0x4D40  ; row 85
    DEFW 0x4E40  ; row 86
    DEFW 0x4F40  ; row 87
    DEFW 0x4860  ; row 88
    DEFW 0x4960  ; row 89
    DEFW 0x4A60  ; row 90
    DEFW 0x4B60  ; row 91
    DEFW 0x4C60  ; row 92
    DEFW 0x4D60  ; row 93
    DEFW 0x4E60  ; row 94
    DEFW 0x4F60  ; row 95
    DEFW 0x4880  ; row 96
    DEFW 0x4980  ; row 97
    DEFW 0x4A80  ; row 98
    DEFW 0x4B80  ; row 99
    DEFW 0x4C80  ; row 100
    DEFW 0x4D80  ; row 101
    DEFW 0x4E80  ; row 102
    DEFW 0x4F80  ; row 103
    DEFW 0x48A0  ; row 104
    DEFW 0x49A0  ; row 105
    DEFW 0x4AA0  ; row 106
    DEFW 0x4BA0  ; row 107
    DEFW 0x4CA0  ; row 108
    DEFW 0x4DA0  ; row 109
    DEFW 0x4EA0  ; row 110
    DEFW 0x4FA0  ; row 111
    DEFW 0x48C0  ; row 112
    DEFW 0x49C0  ; row 113
    DEFW 0x4AC0  ; row 114
    DEFW 0x4BC0  ; row 115
    DEFW 0x4CC0  ; row 116
    DEFW 0x4DC0  ; row 117
    DEFW 0x4EC0  ; row 118
    DEFW 0x4FC0  ; row 119
    DEFW 0x48E0  ; row 120
    DEFW 0x49E0  ; row 121
    DEFW 0x4AE0  ; row 122
    DEFW 0x4BE0  ; row 123
    DEFW 0x4CE0  ; row 124
    DEFW 0x4DE0  ; row 125
    DEFW 0x4EE0  ; row 126
    DEFW 0x4FE0  ; row 127
    DEFW 0x5000  ; row 128
    DEFW 0x5100  ; row 129
    DEFW 0x5200  ; row 130
    DEFW 0x5300  ; row 131
    DEFW 0x5400  ; row 132
    DEFW 0x5500  ; row 133
    DEFW 0x5600  ; row 134
    DEFW 0x5700  ; row 135
    DEFW 0x5020  ; row 136
    DEFW 0x5120  ; row 137
    DEFW 0x5220  ; row 138
    DEFW 0x5320  ; row 139
    DEFW 0x5420  ; row 140
    DEFW 0x5520  ; row 141
    DEFW 0x5620  ; row 142
    DEFW 0x5720  ; row 143
    DEFW 0x5040  ; row 144
    DEFW 0x5140  ; row 145
    DEFW 0x5240  ; row 146
    DEFW 0x5340  ; row 147
    DEFW 0x5440  ; row 148
    DEFW 0x5540  ; row 149
    DEFW 0x5640  ; row 150
    DEFW 0x5740  ; row 151
    DEFW 0x5060  ; row 152
    DEFW 0x5160  ; row 153
    DEFW 0x5260  ; row 154
    DEFW 0x5360  ; row 155
    DEFW 0x5460  ; row 156
    DEFW 0x5560  ; row 157
    DEFW 0x5660  ; row 158
    DEFW 0x5760  ; row 159
    DEFW 0x5080  ; row 160
    DEFW 0x5180  ; row 161
    DEFW 0x5280  ; row 162
    DEFW 0x5380  ; row 163
    DEFW 0x5480  ; row 164
    DEFW 0x5580  ; row 165
    DEFW 0x5680  ; row 166
    DEFW 0x5780  ; row 167
    DEFW 0x50A0  ; row 168
    DEFW 0x51A0  ; row 169
    DEFW 0x52A0  ; row 170
    DEFW 0x53A0  ; row 171
    DEFW 0x54A0  ; row 172
    DEFW 0x55A0  ; row 173
    DEFW 0x56A0  ; row 174
    DEFW 0x57A0  ; row 175
    DEFW 0x50C0  ; row 176
    DEFW 0x51C0  ; row 177
    DEFW 0x52C0  ; row 178
    DEFW 0x53C0  ; row 179
    DEFW 0x54C0  ; row 180
    DEFW 0x55C0  ; row 181
    DEFW 0x56C0  ; row 182
    DEFW 0x57C0  ; row 183
    DEFW 0x50E0  ; row 184
    DEFW 0x51E0  ; row 185
    DEFW 0x52E0  ; row 186
    DEFW 0x53E0  ; row 187
    DEFW 0x54E0  ; row 188
    DEFW 0x55E0  ; row 189
    DEFW 0x56E0  ; row 190
    DEFW 0x57E0  ; row 191

; scroll_y1: centre Y of line-1 letters per scroll frame (start=-27, end=56)
scroll_y1:
    DEFB 229,229,229,229,230,230,230,231,231,232,233,233,234,235,236,237
    DEFB 238,239,240,242,243,244,246,248,249,251,253,255,0,2,4,7
    DEFB 9,11,13,16,18,20,23,25,27,29,31,33,34,36,38,39
    DEFB 41,42,44,45,46,47,48,49,50,51,52,53,53,54,54,55
    DEFB 55,56,56,56,56,56

; scroll_y2: centre Y of line-2 letters per scroll frame (start=-27, end=121)
scroll_y2:
    DEFB 229,229,229,230,230,231,231,232,233,234,235,237,238,240,241,243
    DEFB 245,247,249,252,254,1,3,6,9,12,15,18,22,25,29,33
    DEFB 37,41,45,49,53,57,61,65,69,72,76,79,82,85,88,91
    DEFB 94,96,99,101,103,105,107,109,111,112,114,115,116,117,118,119
    DEFB 120,120,121,121,121,121

; spin_ang: sin_tab index for spin rotation per frame, linear ramp
spin_ang:
    DEFB 0,3,5,8,10,13,16,18,21,23,26,28,31,34,36,39
    DEFB 41,44,47,49,52,54,57,59,62,65,67,70,72,75,78,80
    DEFB 83,85,88,91,93,96,98,101,103,106,109,111,114,116,119,122
    DEFB 124,127,129,132,134,137,140,142,145,147,150,153,155,158,160,163
    DEFB 165,168,171,173,176,178,181,184,186,189,191,194,197,199,202,204
    DEFB 207,209,212,215,217,220,222,225,228,230,233,235,238,240,243,246
    DEFB 248,251,253,0

; orb_scale: extra orbit radius per frame (add to 12), peak ~13 at frame 75
orb_scale:
    DEFB 0,0,0,0,0,0,0,1,1,1,1,1,2,2,2,2
    DEFB 3,3,3,4,4,5,5,5,6,6,7,7,8,8,9,9
    DEFB 10,10,11,11,12,13,13,14,14,15,15,16,16,17,17,18
    DEFB 18,19,19,20,20,21,21,21,22,22,22,23,23,23,24,24
    DEFB 24,24,25,25,25,25,25,25,25,26,26,26,26,26,25,25
    DEFB 25,25,25,25,25,24,24,24,24,23,23,23,22,22,22,21
    DEFB 21,21,20,20,19,19,18,18,17,17,16,16,15,15,14,14
    DEFB 13,13,12,11,11,10,10,9,9,8,8,7,7,6,6,5
    DEFB 5,5,4,4,3,3,3,2,2,2,2,1,1,1,1,1
    DEFB 0,0,0,0,0,0

; orb_phase: per-letter sin_tab index offset for orbit phase stagger
orb_phase:
    DEFB 0,13,27,40,54,67,81,94,108,121,135,148,162,175,189,202,216,229,243

; reset_y1: centre Y of line-1 letters during reset (rest→off-screen)
reset_y1:
    DEFB 56,56,56,55,55,54,54,53,52,50,49,47,46,44,42,40
    DEFB 38,35,33,30,27,24,21,18,15,11,8,4,0,252,248,243
    DEFB 239,234,229

; reset_y2: centre Y of line-2 letters during reset (rest→off-screen)
reset_y2:
    DEFB 121,121,121,120,119,118,117,115,113,111,108,106,103,99,96,92
    DEFB 88,84,80,75,70,65,59,53,47,41,35,28,21,13,6,254
    DEFB 246,238,229

